name: 'Scoped Env'
description: 'A Github action to expose scoped environment variables'
author: 'muchobien'

branding:
  icon: play
  color: blue

inputs:
  secrets:
    description: 'Secrets context to extract secrets from'
    required: true
  scope:
    description: 'Scope of the secrets to expose'
    required: true
  includes:
    description: 'List of secrets to include that are not scoped'
    required: false
  overrides:
    description: 'Shoul override existing environment variables'
    required: false
    default: 'false'
  exporters:
    description: 'List of exporters to use'
    required: false
    default: 'env,output'

runs:
  using: 'node16'
  main: 'dist/index.js'
